config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Doc:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini
        container: qc.doc_clammy-asparagus-duck
timeout: 5400
